### PR TITLE
MINIFI-289: Update test folder to apply linter and set max characters…

### PR DESCRIPTION
**Pull request by phrocker**
… to 200

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by kevdoran** [comment]
Thanks for making all these style changes to the test code @phrocker! At a glance this looks good to me. I'll run a few test builds when I get a chance.

**Comment by apiri** [comment]
reviewing

**Comment by phrocker** [comment]
@apiri rebase complete. Waiting on travis to prove me right/wrong...

**Comment by apiri** [comment]
@phrocker good deal, thanks!  Looks like Travis is happy.  Will scope out from my side to see if that apiri guy is happy too and get this wrapped up

**Comment by apiri** [comment]
looks good, merging

**Pull request closed without merging**
