### PR TITLE
MINIFI-116 Initial Travis CI configuration for Make based build.

### PR DESCRIPTION
**Pull request by apiri**
MINIFI-116 Initial Travis CI configuration for Make based build.

### CODE REVIEW

**Comment by apiri** [comment]
This relies on #15 as well.  Updated it to include that change.

**Comment by trixpan** [comment]
@apiri LGTM

**Comment by trixpan** [comment]
once this is merged it should be easier to expand with CMake and different environments. I am particularly keen to ensure we are able to generate both deb and rpm files

**Comment by apiri** [comment]
@trixpan Yep, sounds good.  Onboard on all counts with that.  Would you like to draw up issues for those packaging formats (maybe one for each for the sake of granularity)?  Definitely getting functional on Windows is a priority.

Also, did you mean to put these comments on #14?  They seem a little more tailored around CMake or maybe I'm just overlooking something.

**Comment by trixpan** [comment]
no no. just thinking about getting travis-ci working asap. Once that is done, evolving the work on #14 - i.e. CMake, windows, etc - should be easier due to the ability of iterating code until we get it right. :-)

Lets get this PR rolling and use it to complete the work started on #14 ;-)

**Comment by apiri** [comment]
@trixpan Thanks for clarifying, let me do some merge magic and we can get rolling.  Glad to have you join in on the minifi-cpp party! 👍

**Pull request merged**
