### PR TITLE
MINIFI-254: Incremental update for linter changes

### PR DESCRIPTION
**Pull request by phrocker**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by apiri** [comment]
This is pretty fantastic and all the changes look good.  Built and ran a simple flow.

Would you mind if I switched around the order of linter and testing in the travis file?

From:
`mkdir ./build && cd ./build && cmake .. && make && make linter && ./tests`
to
`mkdir ./build && cd ./build && cmake .. && make && ./tests  && make linter`

The primary motivation is that in the review process being able to catch the test defects is nice and then if there are minor linting issues, it may or may not require follow up.  In the current scenario, a single linter issue will prevent tests from executing.

Regardless, thanks for cleaning all this up and letting us automate the process using CI.

**Comment by phrocker** [comment]
@apiri I agree with your change. I think in hindsight your approach is much smarter from that perspective.

**Comment by phrocker** [comment]
@apiri squashed.

**Comment by apiri** [comment]
@phrocker code and builds looked good as presented.

unfortunately the rebase after #71 is not a clean one.  I was looking through the conflicts, and they are not overly bad, but was wondering if you would be able to take a look at them?  They are substantiative enough that I think I would want to post a branch for review if I made the changes.

Let me know what works from your side.  Thanks!

**Comment by apiri** [comment]
Verified builds in OS X and Linux **after** rebasing.  😥 

Looks good and verified linter picking up issues for formatting changes.

Will get this merged.

**Pull request closed without merging**
