### PR TITLE
MINIFICPP-2411 Extend NiFi Python API to support source processors

### PR DESCRIPTION
**Pull request by lordgamez**
https://issues.apache.org/jira/browse/MINIFICPP-2411

-------
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by martinzink — APPROVED** [review]

**Review by szaszm — COMMENTED** [review]
LGTM. Is the same API supported by NiFi 2?

**Comment by lordgamez** [comment]
> LGTM. Is the same API supported by NiFi 2?

Yes, this implements the same FlowFileSource API as NiFi 2

**Review by adamdebreceni — APPROVED** [review]

**Review by fgerlits — COMMENTED** [review]
We need to copy the new `processorbase.py` and `flowfilesource.py` files into the Windows installer in `WixWin.wsi.in`, as well.

**Comment by lordgamez** [comment]
> We need to copy the new `processorbase.py` and `flowfilesource.py` files into the Windows installer in `WixWin.wsi.in`, as well.

Good catch, added the files to WiX in 6d44c1f9e36be7b05e48b878eb5c1a53f8f004af

**Review by fgerlits — APPROVED** [review]

**Review by szaszm — APPROVED** [review]

**Pull request closed without merging**
