### PR TITLE
MINIFICPP-1024 - Fix third party dependencies

### PR DESCRIPTION
**Pull request by bakaid**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bakaid** [comment]
> Looks good. I'll run some tests across platforms with various builds enabling and disabling features before merging. thanks!

Thanks, let me know if anything fails. This is a less complete fix than MINIFICPP-1022 will be, but it should make the builds running properly again.

**Comment by phrocker** [comment]
> > Looks good. I'll run some tests across platforms with various builds enabling and disabling features before merging. thanks!
> 
> Thanks, let me know if anything fails. This is a less complete fix than MINIFICPP-1022 will be, but it should make the builds running properly again.

That's a good point. I had a failure on Windows but cleaned out my workspace and am working on another task. I'm good to merge this with a +1 since I haven't had time to re-validate the failure wasn't something in a polluted workspace. If you and @arpadboda already attempted to build and deploy flows w/ PublishKafka on Windows and other platforms I'm good to merge.

**Comment by bakaid** [comment]
> > > Looks good. I'll run some tests across platforms with various builds enabling and disabling features before merging. thanks!
> > 
> > 
> > Thanks, let me know if anything fails. This is a less complete fix than MINIFICPP-1022 will be, but it should make the builds running properly again.
> 
> That's a good point. I had a failure on Windows but cleaned out my workspace and am working on another task. I'm good to merge this with a +1 since I haven't had time to re-validate the failure wasn't something in a polluted workspace. If you and @arpadboda already attempted to build and deploy flows w/ PublishKafka on Windows and other platforms I'm good to merge.

@phrocker I haven't tested PublishKadka under Windows, I'll do it now.

**Comment by bakaid** [comment]
@arpadboda @phrocker I have created a fresh build on Windows and tested PublishKafka with a simple GenerateFlowFile -> PublishKafka flow with a Kafka instance running on the same Windows machine, and it works fine for me.

**Comment by phrocker** [comment]
> @arpadboda @phrocker I have created a fresh build on Windows and tested PublishKafka with a simple GenerateFlowFile -> PublishKafka flow with a Kafka instance running on the same Windows machine, and it works fine for me.

@arpadboda second party validation doesn't hurt. I'll probably be able to get to this later this afternoon ( my time ). if you have a chance to validate sooner let me know.

**Comment by arpadboda** [comment]
Win verification is in progress on my VM.
Merging this, will create a follow-up if I spot anything suspicious.

**Pull request closed without merging**
