### PR TITLE
MINIFICPP-817 - Update cxxopts version to 2.1.2

### PR DESCRIPTION
**Pull request by bakaid**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by bakaid** [comment]
cxxopts is used by minificontroller and extensions/bootstrap/btrsp. Both have been tested manually with the updated version.

**Comment by phrocker** [comment]
Can cxxopts/*test* be removed?

**Comment by bakaid** [comment]
Sure, but then the original CMakeLists.txt has to be modified so that it wont't try to add the test directory as a subdirectory. (The tests are not built by default, by the way.)

**Comment by phrocker** [comment]
It is a policy amongst third party to eliminate tests even if they are turned off. It reduces the size of the download and eliminates unnecessary code.

**Comment by bakaid** [comment]
I agree, just wanted to make sure it's ok to modify the third party this way.
Removed the tests and rebased onto fresh master.

**Comment by bakaid** [comment]
Thank you. The license has not changed, it is identical to the one in our LICENSE file.

**Pull request closed without merging**
