### PR TITLE
MINIFICPP-438: Preform string to correct test failure for verifying t…

### PR DESCRIPTION
**Pull request by phrocker**
…hat json embedded strings will be unescaped

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
My intent was to not form a valid JSON document but to instead continue the spirit of the test.

**Comment by achristianson** [comment]
I looked into this and it's really a problem with the escape/unescape JSON. We're not aiming to parse/unparse a JSON object, but rather to prepare a string for use in JSON. The escape/unescape EL functions use RapidJSON functions to handle the escaping/unescaping by putting the target value into a string JSON object and stripping the quotes.

Your change is correct in spirit that wrapping the string in an object container makes it compatible with RFC4627 and RFC7159.

The change needs to happen in one of these, from Expression.cpp:

```c++
Value expr_escapeJson(const std::vector<Value> &args) {
  const std::string &arg_0 = args[0].asString();
  rapidjson::StringBuffer buf;
  rapidjson::Writer<rapidjson::StringBuffer> writer(buf);
  writer.String(arg_0.c_str());
  std::string result(buf.GetString());
  return Value(result.substr(1, result.length()-2));
}

Value expr_unescapeJson(const std::vector<Value> &args) {
  std::stringstream arg_0_ss;
  arg_0_ss << "\"" << args[0].asString() << "\"";
  rapidjson::Reader reader;
  rapidjson::StringStream ss(arg_0_ss.str().c_str());
  rapidjson::Document doc;
  doc.ParseStream(ss);
  if (doc.IsString()) {
    return Value(std::string(doc.GetString()));
  } else {
    return Value();
  }
}
```

Either the object wrap/unwrap code should be moved here (instead of the test case), or a different technique altogether should be used for JSON escape/unescape.

Feel free to update this PR/add a new PR or I can handle it if you want.

**Comment by achristianson** [comment]
...also I think it would need to be

```json
["string val"]
```
or
```json
{"dummy_key": "string_val"}
```
to really be universally valid, not just

```json
{"string val"}
```
...because there is no key/val pair in that object.

**Comment by phrocker** [comment]
@achristianson i agreed that something else should likely be done. Feel free to take that on. My goal was to solve the test failure.

**Comment by achristianson** [comment]
Fixed the decode method in #290

**Pull request closed without merging**
