### PR TITLE
MINIFICPP-556 Added initial snapcraft build

### PR DESCRIPTION
**Pull request by achristianson**
This wouldn't have been possible without the help of Jeremy Dyer.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
I had a failure after approving. Will retry tomorrow before merging. Might be my issue.

**Comment by achristianson** [comment]
@phrocker The official snap docs recommend building using Ubuntu 16.04. Other environments might not work.

**Comment by jdye64** [comment]
@phrocker were you able to resolve your issues? I didn't experience any problems during my testing.

**Comment by phrocker** [comment]
@jdye64 I was able to with some documentation you provided offline; however, following guides available online previously it failed with the error I sent you. Perhaps it would be useful to add something to the documentation in addition to this snapcraft file?

**Comment by achristianson** [comment]
@jdye64 if you can, please send me the instructions you gave @phrocker. I can add those to the build instructions and update this PR.

**Comment by achristianson** [comment]
Added snap build instructions. Will merge unless there are any further objections.

**Pull request closed without merging**
