### PR TITLE
MINIFI-190: Creating initial commit with additional tests

### PR DESCRIPTION
**Pull request by phrocker**
Additional tests will be updated in separate tickets as needed.

Resolves MINIFI-194 by using a semaphore in place of the
FlowController instance. Stop is performed outside of the
signal handler to avoid synchronicity issues.

Resolves MINIFI-192 by using lock_guard based on a conditional

Resolves issues found with MINIFI-190 regarding GetFile. Added
pragma definitions for GCC < 4.9

### CODE REVIEW

**Comment by phrocker** [comment]
I'll be happy to break this apart

**Comment by phrocker** [comment]
I have found that the flow repository isn't cleaning up after itself. Will resolve that first.

**Comment by apiri** [comment]
Hey @phrocker,

Are you still iterating on this particular PR or is it ready for review?

**Comment by phrocker** [comment]
@apiri  Yes. I just noticed a typo, but it should be ready. It'll probably have some adjustments along the review pipeline, but I don't plan anything else in this PR unless there are comments or things such as typos.

**Comment by phrocker** [comment]
@apiri I did not add the test I have for DataStream and Serializable in this PR, since I'm using it for another PR I'm working on -- this was simply a function of breaking apart PRs. I'll be happy to port those to this PR. I don't typically submit PRs without tests, but also wanted to break the PRs apart. Please advise. It won't be a great deal of work to bring those tests into this branch.

**Comment by apiri** [comment]
@phrocker Flexible either way.  Just wanted to be sure things were getting moved through and incorporated.  Let me know when ready and can scope out then.  Thanks!

**Comment by phrocker** [comment]
@apiri Okay, cool. I think reviewing these changes then allow the subsequent changes to be in a separate PR ( it's coming ) is probably better since those tests encompass other parts of the code too. Plus getting this through sooner with any changes as a result of comments is probably more advantageous.

**Comment by apiri** [comment]
@phrocker Sounds good.  Will scope these out a bit later or over the weekend.

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
Changes look good and was able to verify build and functionality on several environments.  There were a few errant new lines (one of which was in the license header) which I noticed that I will clean up on merge.

**Pull request closed without merging**
