### PR TITLE
MINIFICPP-718: Fix issue with docker verify with docker API changes

### PR DESCRIPTION
**Pull request by phrocker**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
@phrocker I have been bad about verifying this continuously on builds.  Your changes definitely improved the results but I still had failures.  Definitely an improvement and the changes look good but was trying to figure out if the issues are something that should be evaluated a bit more.

**Comment by phrocker** [comment]
@apiri Which test(s) failed?

**Comment by apiri** [comment]
`FAILED
../docker/test/integration/test_zero_file.py::test_minifi_to_nifi INFO:root:Creating tmp test input dir: /tmp/.nifi-test-input.9b64ae83-e438-44a2-a3be-0dc5b091c715
INFO:root:Creating tmp test output dir: /tmp/.nifi-test-output.9b64ae83-e438-44a2-a3be-0dc5b091c715`

The others seem to stem from NiFi version used with some of the changes that went into that:

> 019-01-23 02:59:00,493 ERROR [Site-to-Site Worker Thread-2] o.a.nifi.remote.SocketRemoteSiteListener Unable to communicate with remote instance Peer[url=nifi://minifi-cpp-07dd2475-b383-492a-923d-f23b5579c4f5.nifi-dc9b750b-694e-42de-996a-d9978d4979f0:49452] (SocketFlowFileServerProtocol[CommsID=d55d58b0-1eba-11e9-8983-0242ac1b0003]) due to org.apache.nifi.remote.exception.BadRequestException: org.apache.nifi.remote.exception.ProtocolException: FlowFile exceeds maximum number of attributes with a total of 545608; closing connection\n2019-01-23 02:59:10,411 INFO [Site-to-Site Worker Thread-3] o.a.nifi.remote.SocketRemoteSiteListener Received connection from minifi-cpp-07dd2475-b383-492a-923d-f23b5579c4f5.nifi-dc9b750b-694e-42de-996a-d9978d4979f0/172.27.0.3, User DN: null\n2019-01-23 02:59:10,412 INFO [Site-to-Site Worker Thread-3] o.a.nifi.remote.SocketRemoteSiteListener Successfully negotiated ServerProtocol SocketFlowFileProtocol Version 5 with Peer[url=nifi://minifi-cpp-07dd2475-b383-492a-923d-f23b5579c4f5.nifi-dc9b750b-694e-42de-996a-d9978d4979f0:49454]\n2019-01-23 02:59:10,513 ERROR [Site-to-Site Worker Thread-3] o.a.nifi.remote.SocketRemoteSiteListener Unable to communicate with remote instance Peer[url=nifi://minifi-cpp-07dd2475-b383-492a-923d-f23b5579c4f5.nifi-dc9b750b-694e-42de-996a-d9978d4979f0:49454] (SocketFlowFileServerProtocol[CommsID=db562dbe-1eba-11e9-8983-0242ac1b0003]) due to org.apache.nifi.remote.exception.BadRequestException: org.apache.nifi.remote.exception.ProtocolException: FlowFile exceeds maximum number of attributes with a total of 545608; closing connection\n"

**Comment by phrocker** [comment]
Thanks. I will do a make clean to ensure I have a clean environment. I imagine I didn't see the issues because I had some stale build artifacts

**Comment by apiri** [comment]
@phrocker Sorry for the false alarm.  It does not seem the script pulls the latest image, so I'm assuming I unfortunately had some dev versions of nifi images that conflicted 😦 

Doing a scorched earth approach on all those images got everything working swimmingly.

Will get this merged.

**Pull request closed without merging**
