### PR TITLE
MINIFICPP-1568 Retry PDH processor run to fix test flakiness

### PR DESCRIPTION
**Pull request by lordgamez**
According to @martinzink due to a timing issue the first trigger of the `PerformanceDataMonitor` processor may not contain all the requested counter data, only the following triggers do. Adding the possibility to retry the processor trigger in case the first one fails should remove the flakiness cause by this.

------------------------------------------------
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by martinzink — APPROVED** [review]
LGTM, this should fix the flakyness
10 tries is maybe overkill, but couldnt hurt either

**Comment by szaszm** [comment]
What is the timing issue? Is it unfeasible to eliminate it instead of a workaround in the test?

**Comment by lordgamez** [comment]
> What is the timing issue? Is it unfeasible to eliminate it instead of a workaround in the test?

The timing issue is not in our code, but comes from the Windows OS. After creating the counter we have to let some time pass in order for the OS to gather counter data to be returned when we run the query in the `onTrigger` call. In the first 1-2 calls no data is available yet so the assertions may fail. I hope I'm not mistaken @martinzink may comment further on this.

**Comment by martinzink** [comment]
> What is the timing issue? Is it unfeasible to eliminate it instead of a workaround in the test?

The problem is that the processor opens the windows pdh query in the onschedule function, and collects the data in the ontrigger function.
If there is no usable data in the query then it wont be included in the results.
From microsofts documentation
https://docs.microsoft.com/en-us/windows/win32/perfctrs/collecting-performance-data
Its recommended to wait one second between data collection.

So the onTriggers calls which happen right after the onschedule could lack some fields.

Maybe a cleaner workaround would be if we could schedule the processor separatetly wait a bit than start the triggering, but not sure how big that change would be.

**Comment by szaszm** [comment]
Ok, I see. It sounds like it would be complicated to ensure that onTrigger results in actual data.

**Review by szaszm — APPROVED** [review]

**Review by arpadboda — APPROVED** [review]

**Pull request closed without merging**
