### PR TITLE
MINIFI-70: enhance site2site port negotiation

### PR DESCRIPTION
**Pull request by benqiu2016**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
Hi Bin I think this is ready to merge; however, I saw a test failure in Travis. Any idea what caused this?

**Comment by benqiu2016** [comment]
@phrocker it is run OK in my MAC. run OK in Xcode 7.3 and fail in 8.3 in travis.

**Comment by kevdoran** [comment]
FWIW the tests pass on my Mac as well: MacOS 10.12.5, AppleClang 8.1.0.8020042

**Comment by benqiu2016** [comment]
@phrocker it is passed now after i retrigger the same.

**Comment by phrocker** [comment]
@benqiu2016 I'll get this merged shortly, thanks.

**Pull request closed without merging**
