### PR TITLE
MINIFICPP-264: CompressContent Processor

### PR DESCRIPTION
**Pull request by minifirocks**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by minifirocks** [comment]
implement the compress content, tested with random 100K payload with format gzip, bzip, lzma, xy-lzma. fix the seek issue in stream.

**Comment by phrocker** [comment]
@minifirocks  Can you provide some context regarding "the seek issue in stream?" 

I only see that you changed the variable from a uint64_t to a uint32_t. This reduces the file sizes we can seek within. 

"seek issue" implies a bug. What bug was addressed by changing the primitive?

**Comment by minifirocks** [comment]
@phrocker the basic class is io::BaseStream, the signature is virtual void seek(uint32_t offset) {
the uint64_t break the virtual inheritance.
CompressContext test is running on in my local, it fail in travis, will debug more

**Comment by phrocker** [comment]
@minifirocks Given that we have a need for files bigger than 4gb, we should change all to uint64_t OR the preferred size_t

**Comment by minifirocks** [comment]
@apiri @phrocker fix the test cast, change size and offset signature to uint6_t, it looks like travis passed. please review

**Comment by minifirocks** [comment]
refactor to use lib archive extension.

**Comment by phrocker** [comment]
@minifirocks merging now. I'll take care of the conflict when merging since it's a single line change in the readme.

**Pull request closed without merging**
