### PR TITLE
MINIFI-109: Add ExecuteProcess

### PR DESCRIPTION
**Pull request by benqiu2016**

### CODE REVIEW

**Comment by apiri** [comment]
Reviewing

**Comment by benqiu2016** [comment]
@apiri Address the above review comments. Thanks for the review.

**Comment by apiri** [comment]
@benqiu2016 Looks good here!  Will merge in and thanks for the contribution.

**Comment by randerzander** [comment]
@benqiu2016 @apiri saw that this got committed to master.

Unfortunately, I'm getting build errors that strcpy and strtok are not members of 'std'. Including some build environment info and the errors produced.

[root@d0a671fc9da1 nifi-minifi-cpp]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@d0a671fc9da1 nifi-minifi-cpp]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@d0a671fc9da1 nifi-minifi-cpp]# yum install -y boost-devel libxml2-devel
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.umflint.edu
 * extras: mirror.trouble-free.net
 * updates: mirrors.centos.webair.com
Package boost-devel-1.53.0-25.el7.x86_64 already installed and latest version
Package libxml2-devel-2.9.1-6.el7_2.3.x86_64 already installed and latest version
Nothing to do
[root@d0a671fc9da1 nifi-minifi-cpp]# make
mkdir -p ./build
mkdir -p ./target
make -C thirdparty/uuid
make[1]: Entering directory `/nifi-minifi-cpp/thirdparty/uuid'
gcc -g -Wall -rdynamic  -O0 -ggdb -g3 -fexceptions -Wno-write-strings -fvisibility=hidden -fPIC -I.. ./tst_uuid.c  libuuid.a -o ./tst_uuid
make[1]: Leaving directory `/nifi-minifi-cpp/thirdparty/uuid'
g++ -Os -fexceptions -fpermissive -Wno-write-strings -std=c++11 -fPIC -Wall -g -Wno-unused-private-field -I./inc -I./src -I./test -I./thirdparty -I/usr/include/libxml2 -I./thirdparty/yaml-cpp-yaml-cpp-0.5.3/include -o build/ExecuteProcess.o -c src/ExecuteProcess.cpp
src/ExecuteProcess.cpp: In member function 'virtual void ExecuteProcess::onTrigger(ProcessContext*, ProcessSession*)':
src/ExecuteProcess.cpp:101:2: error: 'strcpy' is not a member of 'std'
  std::strcpy(cstr, _fullCommand.c_str());
  ^
src/ExecuteProcess.cpp:101:2: note: suggested alternative:
In file included from ./inc/TimeUtil.h:25:0,
                 from src/ExecuteProcess.cpp:20:
/usr/include/string.h:125:14: note:   'strcpy'
 extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
              ^
src/ExecuteProcess.cpp:102:12: error: 'strtok' is not a member of 'std'
  char *p = std::strtok (cstr, " ");
            ^
src/ExecuteProcess.cpp:102:12: note: suggested alternative:
In file included from ./inc/TimeUtil.h:25:0,
                 from src/ExecuteProcess.cpp:20:
/usr/include/string.h:344:14: note:   'strtok'
 extern char *strtok (char *__restrict __s, const char *__restrict __delim)
              ^
src/ExecuteProcess.cpp:108:7: error: 'strtok' is not a member of 'std'
   p = std::strtok(NULL, " ");
       ^
src/ExecuteProcess.cpp:108:7: note: suggested alternative:
In file included from ./inc/TimeUtil.h:25:0,
                 from src/ExecuteProcess.cpp:20:
/usr/include/string.h:344:14: note:   'strtok'
 extern char *strtok (char *__restrict __s, const char *__restrict __delim)
              ^
src/ExecuteProcess.cpp:198:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (numRead == (sizeof(buffer) - totalRead))
                                                 ^

**Comment by apiri** [comment]
hey @randerzander would you mind please opening a ticket in JIRA to report this so we can track appropriately?  https://issues.apache.org/jira/browse/MINIFI

**Comment by randerzander** [comment]
Will do. I assumed you would have considered it part of the original
ExecuteProcess jira. Will reply here shortly

On Sep 29, 2016 9:21 AM, "Aldrin Piri" <notifications@github.com> wrote:

hey @randerzander <https://github.com/randerzander> would you mind please
opening a ticket in JIRA to report this so we can track appropriately?
https://issues.apache.org/jira/browse/MINIFI

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/nifi-minifi-cpp/pull/13#issuecomment-250463867>,
or mute the thread

**Comment by apiri** [comment]
Thanks!  Just makes it a little easier to cover as that one was closed out.  Much appreciated.  Was able to reproduce on a Linux environment.

**Comment by randerzander** [comment]
I have opened https://issues.apache.org/jira/browse/MINIFI-111

**Comment by apiri** [comment]
@randerzander Great, thanks!

**Pull request closed without merging**
