### PR TITLE
MINIFI-224 - fixes for locating ZLIB on Ubuntu 16.10 devices

### PR DESCRIPTION
**Pull request by jdye64**

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
Hey @jdye64,

I was unable to recreate this using the Ubuntu 16.10 Docker image before patch.  Could you specify some additional information concerning the environment that triggered it?  Additionally,  it looks like there was a build issue https://s3.amazonaws.com/archive.travis-ci.org/jobs/205337185/log.txt in Travis.

**Comment by jdye64** [comment]
@apiri The environment where I was experiencing these issues was a niche environment really outside of the normal setup. Also I have found a better way to handle this situation in that specific environment. I'm going to close this PR as I do not think it is needed any longer.

**Comment by apiri** [comment]
Okay, going to also close the associated JIRA.

**Pull request closed without merging**
