### PR TITLE
MINIFICPP-2441: Refactored Creating Properties via to_array to Auto Determine Number of Properties

### PR DESCRIPTION
**Pull request by james94**
Addresses Jira Ticket Created by @fgerlits: https://issues.apache.org/jira/browse/MINIFICPP-2441

@szaszm @lordgamez @martinzink 

**Description**: Across Processors and ControllerServices, we previously determined the number of properties by manually specifying it to create the static properties using std::array. 

**Result**: With this update, for properties that consist of more than 0, we switch to using C++20's std::to_array<>({prop1, prop2, etc}) to automatically determine the number of properties using list comprehension. Thus, for MiNiFi Processors and ControllerServices that had at least 1 property or more, we used this std::to_array approach to do the conversion of PropertyDefinition objects to PropertyReference objects. In the case that we had Processors or ControllerServices that had 0 properties, we still needed to use the previous approach of manually specifying that there were 0 properties. After building MiNiFi C++ with these updates, I was able to launch minifi and all 275 CTESTs passed.

**Steps**: I also verified that I could build and run MiNiFi C++ using the following commands:

~~~bash
# conanfile.py is in root dir of MiNiFi C++ project
cd $HOME/nifi-minifi-cpp

mkdir build_cmake
cd build_cmake

# create MINIFI_HOME env variable for binary executable minifi
export MINIFI_HOME=$(pwd)

# Generate build OS files using CMake (I built on Ubuntu 22.04)
cmake .. -DCMAKE_BUILD_TYPE=Debug

# Build MiNiFi
make -j $(nproc)

# Run minifi binary executable
./bin/minifi

# Check CTESTs
ctest
~~~

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by fgerlits — COMMENTED** [review]
LGTM, but can you fix the linter errors, please? I know you did not introduce them, but there aren't too many, and it would be good to see more green CI jobs.

**Comment by james94** [comment]
Thanks for the quick response @fgerlits . Yeah I can look at the linter errors coming from python scripts. I'll check them and make the updates.

**Comment by james94** [comment]
@fgerlits I updated the PutFile.h's public and private class specifier adding a blank line before them. When you get a chance, can you approve CI/CD workflow, so I can check if they pass?

**Comment by james94** [comment]
@fgerlits CI/CD was complaining about some trailing whitespace in PutFile.h, I removed the trailing whitespace and also enabled my local VS code to remove trailing whitespace from now on. Can you approve the CI/CD workflow, so I can see if it passes this time?

**Comment by james94** [comment]
CI/CD workflow passed for each OS. I believe this PR is ready to be merged into MiNiFi's main branch. @fgerlits

**Review by martinzink — APPROVED** [review]
Lgtm thanks for the refactor

**Review by fgerlits — APPROVED** [review]

**Review by lordgamez — APPROVED** [review]
LGTM, thanks!

**Review by szaszm — APPROVED** [review]
thanks for the contribution! :)

**Pull request closed without merging**
