### PR TITLE
MINIFI-235: Resolve hostname ident

### PR DESCRIPTION
**Pull request by phrocker**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by randerzander** [comment]
Tested this in CentOS7 in docker, as well as from one physical host to another. All works as expected using shortnames and fqdns.

**Comment by phrocker** [comment]
@randerzander  big thanks for testing this for me!

**Comment by jdye64** [comment]
reviewing

**Comment by jdye64** [comment]
Tested using official MiNiFi Docker image against official NiFi Docker image running on Mac OS X host. Was able to successfully transfer flowfiles from minifi to nifi using fqdn where previously only ip address worked. Thanks @randerzander for pointing that out and @phrocker for the quick fix.

**Pull request closed without merging**
