### PR TITLE
MINIFICPP-1508 Remove the legacy Regex wrapper and use std::regex ins…

### PR DESCRIPTION
**Pull request by martinzink**
…tead

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by szaszm — APPROVED** [review]
Thanks for cleaning this up. LGTM.

**Review by adamdebreceni — APPROVED** [review]

**Review by fgerlits — APPROVED** [review]

**Review by lordgamez — APPROVED** [review]
Integration test failure looks to be an unrelated transient failure as it ran successfully locally multiple times. Thanks for the cleanup!

**Review by fgerlits — CHANGES_REQUESTED** [review]
I don't know why, but the `features/http.feature:24  A MiNiFi instance sends data through a HTTP proxy and another one listens` Docker integration test fails in CI after I apply this change, and it passes without this change.

I have rerun the CI job 3 times, and each time it failed.  If I run the Docker tests locally, they pass.

Can you try rebasing this PR on top of the current main and check if the Docker CI job passes, please?

**Review by fgerlits — APPROVED** [review]

**Review by arpadboda — APPROVED** [review]

**Comment by arpadboda** [comment]
Merged in 1fb7540d8ea6325d39c65a0c6769e6e87eda983c
(Sorry, messed up the commit msg)

**Pull request closed without merging**
