### PR TITLE
MINIFICPP-303 Upgrade civetweb and rocksdb

### PR DESCRIPTION
**Pull request by calebj**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by achristianson** [comment]
Looks good.

**Comment by achristianson** [comment]
I can build & make test this on CentOS 7.4 with devtoolset-6 (GCC 6.3.1), but it fails when using devtoolset-7 (GCC 7.1.1).

```
In file included from /home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/write_batch_internal.h:12:0,
                 from /home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/column_family.h:20,
                 from /home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/version_set.h:31,
                 from /home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/compaction.h:11,
                 from /home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/compaction_iterator.h:12,
                 from /home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/builder.cc:16:
/home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/write_thread.h: In member function ‘std::mutex& rocksdb::WriteThread::Writer::StateMutex()’:
/home/achristianson/workspace/nifi-minifi-cpp/thirdparty/rocksdb/db/write_thread.h:225:78: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
       return *static_cast<std::mutex*>(static_cast<void*>(&state_mutex_bytes));
```

I would still merge this because I wasn't able to build with devtoolset-7 before this change, either. It's an improvement to have the newer versions, and I can't find any regressions.

**Comment by phrocker** [comment]
@calebj can you define a top level variable for the path to civet and rocksdb and use that instead of the hardcoded path?

**Comment by phrocker** [comment]
@calebj did anything in the process change? I can't build "No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()" Usually this indicates a version issue but I have version 3.10 on mac.

**Comment by calebj** [comment]
Weird. Nothing in the process should have changed. Where is that happening?

**Comment by phrocker** [comment]
CMake Error at /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/WriteBasicConfigVersionFile.cmake:40 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/CMakePackageConfigHelpers.cmake:207 (write_basic_config_version_file)
  CMakeLists.txt:644 (write_basic_package_version_file)

I don't see this in a rocksdb 5.8 clean checkout. I'm on OSX.

**Comment by calebj** [comment]
See if it works after the next push. I'm putting 5.8.6 in afresh and disabling the tests in a cleaner fashion.

**Comment by phrocker** [comment]
@calebj Re the next push, did you force push into that last commit?

**Comment by calebj** [comment]
I did. The new commit messages reflect the new version, too.

**Comment by phrocker** [comment]
@calebj the travis failure shows you what we've been seeing on clang 9

https://travis-ci.org/apache/nifi-minifi-cpp/jobs/309102064

It might be better to separate the upgrade of civet and rocksdb?

**Comment by phrocker** [comment]
@calebj I see the change. I'll attempt to merge this into master and run the build before pushing. thanks!

**Comment by phrocker** [comment]
@calebj I merged this already, but the sync hasn't occurred. Sometimes we need to perform another merge to break it free

https://git-wip-us.apache.org/repos/asf?p=nifi-minifi-cpp.git for reference.

**Comment by calebj** [comment]
I see it in df353561c8a8a0a0d1178a76f03b966b44542834. Hopefully that commit hash will resolve once the sync is complete. Thanks!

**Pull request closed without merging**
