### PR TITLE
Providing fixes for sourcing RHEL based distributions in the bootstrap process

### PR DESCRIPTION
**Pull request by apiri**
Providing fixes for sourcing RHEL based distributions in the bootstrap process

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ X] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
@apiri what was the problem you were experiencing and on what distro specifically? I don't see an issue on the clean rhel distros I have running now,

**Comment by phrocker** [comment]
These changes look good at face value. I'm going to try it across a few platforms and await travis completion before merging. Thanks!

**Comment by apiri** [comment]
Updated the script to determine the directory in which it resides and then uses that to generate a full path for each environment file sourced.  Verification on OS X looks like behavior remains constant and this additionally resolves the issues that were present in CentOS & Fedora.

**Comment by phrocker** [comment]
@apiri looks good. will merge.

**Pull request closed without merging**
