### PR TITLE
MINIFICPP-1752 Remove the catch2 dependency from our the test infrast…

### PR DESCRIPTION
**Pull request by martinzink**
…ructure

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by lordgamez — COMMENTED** [review]
[In another PR](https://github.com/apache/nifi-minifi-cpp/pull/1255) I had to change `libminifi/include/utils/TestUtils.h` because I found that it also has a dependency to catch2 with a single `REQUIRE` call, maybe that could also be removed as part of this PR.

**Comment by martinzink** [comment]
> [In another PR](https://github.com/apache/nifi-minifi-cpp/pull/1255) I had to change `libminifi/include/utils/TestUtils.h` because I found that it also has a dependency to catch2 with a single `REQUIRE` call, maybe that could also be removed as part of this PR.

Good idea, https://github.com/apache/nifi-minifi-cpp/pull/1261/commits/be3f276dc4005e6c3218486f01c9dd126e84bee6

**Comment by szaszm** [comment]
The windows job failure seems to be related

**Comment by szaszm** [comment]
And another question: does this change benefit the codebase aside from the upcoming GCS extension? E.g. do we save compilation time?
If not, maybe it would be better for GCS to not rely on these utilities, or only depend on a limited set of them. I don't expect many too many dependencies in the future that mandate their own test framework.

**Comment by martinzink** [comment]
> And another question: does this change benefit the codebase aside from the upcoming GCS extension? E.g. do we save compilation time? If not, maybe it would be better for GCS to not rely on these utilities, or only depend on a limited set of them, and keep the extra complexity of dealing with Google's BS inside the extension. I don't expect many too many dependencies in the future that mandate their own test framework.

I dont think that there is measurable difference if any. But I do think this improves the codebase because it removes an unneccessary direct dependency.
The utilities in TestBase.h and SingleInputTestController.h dont rely on Catch2 so this change is really an _include what you use_ refactor, because I think our catch tests should include the catch headers and not get them indirectly from TestBase.h

Also without TestBase.h I think the quality of the GCS tests would greatly decrease (or bring in some code duplication)
Besides the GCS extension we could also use gtest to create [death tests](https://google.github.io/googletest/advanced.html#death-tests) (catch2 doesnt support those yet iirc)

Overall I might agree that the upside is not that great, but I dont really see a downside to this change either.

**Review by fgerlits — APPROVED** [review]

**Review by lordgamez — APPROVED** [review]

**Review by adamdebreceni — APPROVED** [review]

**Review by szaszm — APPROVED** [review]

**Comment by szaszm** [comment]
During a pre-merge check, I got this compilation error:
```
/home/szaszm/nifi-minifi-cpp-3/extensions/expression-language/tests/ProcessContextExprTests.cpp:54:10: error: expected constructor, destructor, or type conversion before ‘(’ token
   54 | TEST_CASE("ProcessContextExpr can update existing processor properties", "[setProperty][getProperty]") {
      |          ^
make[2]: *** [extensions/expression-language/tests/CMakeFiles/ProcessContextExprTests.dir/build.make:76: extensions/expression-language/tests/CMakeFiles/ProcessContextExprTests.dir/ProcessContextExprTests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:9470: extensions/expression-language/tests/CMakeFiles/ProcessContextExprTests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Could you fix it? We just need another Catch.h include in ProcessContextExprTests.cpp, but I don't want to change files in a merge commit.

**Pull request closed without merging**
