### PR TITLE
MINIFI-304: Update testing strategy

### PR DESCRIPTION
**Pull request by phrocker**
MINIFI-306: Move Docs and Docker cmake code into a separate module.
this will clean-up the end of the file. We will continue to do cleanup
but this has a great impact to improve the readability of the root
cmake

MINIFI-305: Add header to iOS.cmake module

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by kevdoran** [comment]
LGTM, but we may also want to take a look at the CMake integration approach provided by Catch ([ParseAndAddCatchTests.cmake](https://github.com/philsquared/Catch/blob/master/contrib/ParseAndAddCatchTests.cmake)), which will automatically scan from tests and add them: https://github.com/philsquared/Catch/blob/master/docs/build-systems.md

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
@phrocker These changes look good and good to merge.  Would it be easier if we wait for #83 to finalize and merge first?

@kevdoran Definitely worth exploring.  Want to create a JIRA and we can evaluate at some point?

**Comment by kevdoran** [comment]
@aldrin I created MINIFI-319 to track the CMake Catch scanning.

**Comment by phrocker** [comment]
@apiri I would prefer to wait on #83 .

**Comment by apiri** [comment]
Sounds good.  We can finish that up and go from there.

**Comment by apiri** [comment]
@phrocker I got #83 in, would you be able to please rebase this on master?

**Comment by apiri** [comment]
Thanks for the rebase.  Ran through the usual battery of stuff and looks good.  Will get this merged.

**Pull request closed without merging**
