### PR TITLE
Minifi 109

### PR DESCRIPTION
**Pull request by benqiu2016**

### CODE REVIEW

**Comment by apiri** [comment]
hey @benqiu2016.  It looks like there are some merge conflicts and I wasn't able to just apply the last commit.  Is there a way you can get this rebased on master?

**Comment by benqiu2016** [comment]
@apiri, will do. Thanks.

**Comment by apiri** [comment]
Hey @benqiu2016,

Looks like this one was superseded by #13.  Could you please close this when you have the opportunity?

**Comment by benqiu2016** [comment]
Close as Aldrin suggested.

**Pull request closed without merging**
