### PR TITLE
MINIFI-286: Fix compilation error when GCC version is greater than 4.9

### PR DESCRIPTION
**Pull request by jdye64**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
Hey @jdye64,

I was not able to make the current codebase fail under Ubuntu 17.04 which has gcc 6.3.0 (12ubuntu2).  Any other considerations of your environment?

**Comment by phrocker** [comment]
@apiri The logic can be improved  @jdye64 I'm in favor of removing the conditional expression entirely and using the c style for all versions since that will work. There's no point in using the C++ regex matching since it won't be available for all builds. If you really want to maintain it, you can do this:

```
diff --git a/libminifi/src/processors/GetFile.cpp b/libminifi/src/processors/GetFile.cpp
index 2740793..9988029 100644
--- a/libminifi/src/processors/GetFile.cpp
+++ b/libminifi/src/processors/GetFile.cpp
@@ -24,8 +24,9 @@
 #include <dirent.h>
 #include <limits.h>
 #include <unistd.h>
-#if  (__GNUC__ >= 4)
-#if (__GNUC_MINOR__ < 9)
+// if an older version of gcc that doesn't support <regex>
+#ifdef __GNUC__
+#if (__GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ < 9))
 #include <regex.h>
 #else
 #include <regex>
@@ -268,8 +269,7 @@ bool GetFile::acceptFile(std::string fullName, std::string name,
       return false;
 
 #ifdef __GNUC__
-#if (__GNUC__ >= 4)
-#if (__GNUC_MINOR__ < 9)
+#if (__GNUC__ < 4 || (__GNUC__ == 4 && __GNUC_MINOR__ < 9))
     regex_t regex;
     int ret = regcomp(&regex, request.fileFilter.c_str(), 0);
     if (ret)
@@ -280,7 +280,7 @@ bool GetFile::acceptFile(std::string fullName, std::string name,
       return false;
 #else
     try {
-      std::regex re(fileFilter);
+      std::regex re(request.fileFilter);
 
       if (!std::regex_match(name, re)) {
         return false;
@@ -290,7 +290,6 @@ bool GetFile::acceptFile(std::string fullName, std::string name,
       return false;
     }
 #endif
-#endif
 #else
     logger_->log_info("Cannot support regex filtering");
 #endif
```

**Comment by jdye64** [comment]
I like just removing the conditional expression. I'm going to update to that now.

**Comment by apiri** [comment]
cool, looks good and was able to verify the issue beforehand with a specific docker environment that hit the bad logic.  I did notice there was a linter issue but I can take care of that on merge

Thanks for correcting this!

**Pull request closed without merging**
