### PR TITLE
MINIFI-6: Basic C++ implementation for MiNiFi

### PR DESCRIPTION
**Pull request by benqiu2016**

### CODE REVIEW

**Comment by simonellistonball** [comment]
Tried building this with the default settings (-O0), which yields 1.3MB binary. Is the intention to provide a different build script for more constrained environments, (-Os yields 459K binary).

**Comment by apiri** [comment]
Reviewing and testing.  Will leave comments as they arise.

**Comment by apiri** [comment]
Hey @benqiu2016.  I've had the opportunity to review this and scope out the functionality with the help of your README and it seems to be working well in communicating with the NiFi instance.  To get a bit more granular, I was thinking of merging this into the ongoing MINIFI-6 branch so we can continue to iterate and evolve and maybe break things down a bit further.

Overall, the functionality has been great and working quite well.  I've had success with the code on OS X and a couple distros of Linux.

Let me know your thoughts!

**Comment by benqiu2016** [comment]
@apiri 
It sounds good. Thanks.

**Comment by apiri** [comment]
Hey @benqiu2016.  I have rebased and merged this effort and pushed it to nifi-minifi-cpp/MINIFI-6 as part of 9e42ec5f3fdb0804b5977fb1abd8128f612fc71f.  As it is not yet in master, the PR wasn't automatically closed out.  Would you be able to close this out when you have the opportunity?

**Pull request closed without merging**
