### PR TITLE
MiNiFi-168 enable minifi cpp agents to be able to receive flow files

### PR DESCRIPTION
**Pull request by rkarthik29**

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
@rkarthik29 this does not seem to work in the current environment.  I have created a NiFi flow with an output port.  I can send to it from MiNiFi and pull via another NiFi instance, but this is not working with your PR.  Did you capture all your files on your commit?

Could you specify your configuration if I am overlooking something?

Thanks!

**Comment by rkarthik29** [comment]
`Flow Controller:
    name: MiNiFi Flow

Processors:
    - name: LogAttribute
      class: org.apache.nifi.processors.standard.LogAttribute
      max concurrent tasks: 1
      scheduling strategy: TIMER_DRIVEN
      scheduling period: 1 sec
      penalization period: 30 sec
      yield period: 1 sec
      run duration nanos: 0
      auto-terminated relationships list:
      Properties:
          Log Level: error
          Log prefix: Zoomba says
          Log Payload: true

Connections:
    - name: Get files from nifi
      source name: 1d850ad3-0159-1000-7ee1-de9577f40ca3
      source relationship name: undefined
      destination name: LogAttribute
      max work queue size: 0
      max work queue data size: 1 MB
      flowfile expiration: 600 sec
    - name: back to nifi
      source name: LogAttribute
      source relationship name: success
      destination name: 1e0c7440-0159-1000-2272-7d0521e5059b
      max work queue size: 0
      max work queue data size: 1 MB
      flowfile expiration: 600 sec

Remote Processing Groups:
    - name: NiFi Flow
      url: http://karthiksinstance:8080/nifi
      timeout: 30 secs
      yield period: 10 sec
      Input Ports:
          - id: 1e0c7440-0159-1000-2272-7d0521e5059b
            name: 1e0c7440-0159-1000-2272-7d0521e5059b
            max concurrent tasks: 1
            Properties:
                Port: 19001
                Host Name: karthiksinstance
      Output Ports:
          - id: 1d850ad3-0159-1000-7ee1-de9577f40ca3
            name: 1d850ad3-0159-1000-7ee1-de9577f40ca3
            max concurrent tasks: 1
            Properties:
                Port: 19001
                Host Name: karthiksinstance`

this is the config i used. I checked my code base and i have checked in the latest that i build a worked agains. i will try and rerun the test and confirm

**Comment by jdye64** [comment]
Sense this is proving a little tricky to validate I'm going to make a docker compose environment so that we can all be on the same page when testing. Seems like the configuration is a little finicky and if anything the similar container environment might help us track those problems down as well. I will share the link to the containers hopefully here shortly after I validate on my local machine. Also I would like to add some documentation to the scope of this PR since this is something people will be wanting to understand how to do frequently.

**Comment by jdye64** [comment]
@apiri and @rkarthik29  I was able to get this working with this docker container environment. You can use the exact setup I did by running ....

git clone https://github.com/jdye64/minifi-cpp-devenvs.git && cd minifi-cpp-devenvs/int-envs/0.2.0/MINIFI-168 && docker-compose up -d && sleep 45 && open localhost:8080/nifi

This assumes that you have Docker, Docker-compose, and git already installed on your local machine. This will also sleep for 45 seconds and open up the NiFi UI where you can see the activity flowing both ways as well.

Keep in mind the initial download of the images will be quite large so it might require a little patience. Hopefully this helps us all get on the same page with the testing however.

**Comment by apiri** [comment]
Looks good.  I was able to start with a fresh install of NiFi and minifi and get it running.  Will merge this in.

**Pull request closed without merging**
