### PR TITLE
MINIFICPP-1289 add range-v3 and examples

### PR DESCRIPTION
**Pull request by szaszm**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by fgerlits — APPROVED** [review]
This is great!  I'm looking forward to being able to use ranges.

**Review by adamdebreceni — APPROVED** [review]

**Review by lordgamez — APPROVED** [review]
Great addition to the codebase :+1:

**Comment by szaszm** [comment]
Updated range-v3 from 0.11.0 (latest release) to [c6d7c74](https://github.com/ericniebler/range-v3/commit/c6d7c7480ebdb7f3fcc124c8fdd1b48f7a5adf39), because after rebasing to partial C++20-enabled main, the AppleClang build broke. Related range-v3 issue: https://github.com/ericniebler/range-v3/issues/1604

Please let me know if you still approve the changes, or would rather not depend on a non-release version.

**Comment by fgerlits** [comment]
Using an unreleased version until there is a 0.11.1 release available is OK.  I'd probably use the newest version available instead of the oldest version which contains this fix, but I'm fine with either option.

**Review by fgerlits — APPROVED** [review]

**Review by lordgamez — APPROVED** [review]

**Review by adamdebreceni — APPROVED** [review]

**Pull request closed without merging**
