### PR TITLE
MINIFI-229 - Remove third party tests from project

### PR DESCRIPTION
**Pull request by jdye64**

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
hey @jdye64,

I like the same functionality with less code and quicker build times!  This is great.

One small thing is that I believe this completely removes inclusion of Google Test.  If this seems on track with your expectations, could you also please update the LICENSE to reflect this?

Thanks!

**Comment by jdye64** [comment]
@apiri yes this was my intention. I have removed it from the LICENSE in this commit.

**Comment by apiri** [comment]
Great, thanks!  Will get this merged.

**Pull request closed without merging**
