### PR TITLE
MINIFICPP-1898 - Fix ListenHTTP test failure

### PR DESCRIPTION
**Pull request by adam-markovics**
https://issues.apache.org/jira/browse/MINIFICPP-1898

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by fgerlits — APPROVED** [review]
Can you put some explanation in either the PR description or the Jira, please?  Was the default implementation of these two HTTP handlers no-op in the older CivetWeb version, and changed to `assert(false)` in the new version?

**Comment by adam-markovics** [comment]
CivetWeb's default implementations for request handlers (including PUT and DELETE) return error codes, indicating they didn't handle the request (returning `false`). Then control flow goes on a strange way, using `goto` to jump inside a function. Earlier version of the library didn't have an assert on this path, the new one does. It's saying "we have a handler, but we don't". So my answer to this is providing overriding handlers in the user code.

Also commented on the JIRA ticket.

**Review by fgerlits — CHANGES_REQUESTED** [review]
Not strictly related, but there is a Clang Tidy check failure in `ListenHTTPTests.cpp`, line 183:
```
/home/runner/work/nifi-minifi-cpp/nifi-minifi-cpp/extensions/civetweb/tests/ListenHTTPTests.cpp:183:15:
error: the 'empty' method should be used to check for emptiness instead of comparing to an empty object [readability-container-size-empty,-warnings-as-errors]
      REQUIRE("" == response_body);
              ^~~~~~~~~~~~~~~~~~~
              response_body.empty()
```

I think this small fix could be included in this PR.  Either changing the check to `.empty()` or adding a `NOLINT` comment would be fine.

**Comment by adam-markovics** [comment]
> Not strictly related, but there is a Clang Tidy check failure in `ListenHTTPTests.cpp`, line 183:
> 
> ```
> /home/runner/work/nifi-minifi-cpp/nifi-minifi-cpp/extensions/civetweb/tests/ListenHTTPTests.cpp:183:15:
> error: the 'empty' method should be used to check for emptiness instead of comparing to an empty object [readability-container-size-empty,-warnings-as-errors]
>       REQUIRE("" == response_body);
>               ^~~~~~~~~~~~~~~~~~~
>               response_body.empty()
> ```
> 
> I think this small fix could be included in this PR. Either changing the check to `.empty()` or adding a `NOLINT` comment would be fine.

Good Idea. I fixed it.

**Review by fgerlits — APPROVED** [review]

**Review by martinzink — APPROVED** [review]

**Comment by szaszm** [comment]
While this makes the test green, ListenHTTPTests are also running awfully long now, for almost 2 minutes, regularly. Could you have a look into why is this the case? It used to take about 10 seconds (which is still on the longer side), or 1/10 of the current runtime, before the issue was introduced in 287fe85.

**Review by lordgamez — APPROVED** [review]

**Comment by adam-markovics** [comment]
> While this makes the test green, ListenHTTPTests are also running awfully long now, for almost 2 minutes, regularly. Could you have a look into why is this the case? It used to take about 10 seconds (which is still on the longer side), or 1/10 of the current runtime, before the issue was introduced in [287fe85](https://github.com/apache/nifi-minifi-cpp/commit/287fe853822880c083728d8d03b00f9c5c1321ef).
> 
> edit: To be clear, I tested [287fe85](https://github.com/apache/nifi-minifi-cpp/commit/287fe853822880c083728d8d03b00f9c5c1321ef), the issue was introduced in the commit after that, [0bf8ce9](https://github.com/apache/nifi-minifi-cpp/commit/0bf8ce968bdebfa6867eb339049bfabca19e5df0).

It looks like this comes from the CivetWeb version upgrade. Just changing that makes ListenHTTPTests run faster. I'm looking if we can do anything on the user side.

**Comment by adam-markovics** [comment]
This pull request doesn't make ListenHTTPTests run slower. On main it is the same time (1 minute 45 seconds) as with this PR, measured in release.
In debug, main fails very fast, while this PR runs for roughly the same time as in release, and it passes.
If we want to understand why it's running slower than 287fe85, it's something CivetWeb internal, and very not obvious to understand.
I think it is a separate issue and should be handled in a different PR if we dedicate resources to that.

**Pull request closed without merging**
