### PR TITLE
MINIFICPP-382: Implement SUSE release support for SUSE and SLES12

### PR DESCRIPTION
**Pull request by phrocker**
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
How fitting, a unit test is seg faulting....I'll check and update.

**Comment by apiri** [comment]
grabbed me some ISOs, will scope out

**Comment by minifirocks** [comment]
Looks good.

**Comment by apiri** [comment]
@phrocker I had run into a small hiccup when initially reviewing on SLES 12 SP3 which was probably more a product of my lack of familiarity with SUSE.  I needed to first enable the SLES SDK repository after activating my install.  This was accomplished via yast.  After that, I was able to pull down all the devel dependencies.  Build and testing went fine.  +1 from me.  Might be helpful to have a note about that dependency first.  not sure if bootstrap or readme makes more sense.

**Comment by phrocker** [comment]
@apiri I made an update to the readme last night. 

https://github.com/apache/nifi-minifi-cpp/pull/260/commits/7a3e81066c007053adc77a315f490e44671cbd34

**Comment by apiri** [comment]
@phrocker great, thanks will get this merged. sorry didn't notice the update.

**Pull request closed without merging**
