### PR TITLE
MINIFI-274 Use external project with existing source for jsoncpp to

### PR DESCRIPTION
**Pull request by apiri**
MINIFI-274 Use external project with existing source for jsoncpp to avoid contamination of core project build.

This was done in a minimal fashion to solve the issue before delving too much into restructuring current format to make use of ExternalProjects for the remaining dependencies.
 
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

### CODE REVIEW

**Comment by brosander** [comment]
Reviewing

**Comment by apiri** [comment]
@brosander just noticed there was a merge conflict from one of the prior merges I performed.  will fix up quickly.

**Comment by brosander** [comment]
+1 merging

**Comment by apiri** [comment]
@brosander Okay, rebased on latest master and have pushed to update.  Thanks for scoping out.

**Comment by apiri** [comment]
@brosander looks like some of the environment issues have been ironed out and things look good in Travis, OSX 10.11, & Ubuntu 17.04.

**Comment by brosander** [comment]
@apiri I'll take a look, thanks!

**Comment by brosander** [comment]
definitely better but I still seem to be getting a segfault on the s2s test

**Comment by brosander** [comment]
```
TestSiteToSiteVerifySend
-------------------------------------------------------------------------------
/home/bryan/Github/nifi-minifi-cpp/libminifi/test/unit/Site2SiteTests.cpp:102
...............................................................................

/home/bryan/Github/nifi-minifi-cpp/libminifi/test/unit/Site2SiteTests.cpp:102: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```

**Comment by apiri** [comment]
@brosander could you list your environment?

**Comment by brosander** [comment]
Ubuntu 16.04 64 bit (latest LTS release of Ubuntu) I'll craft a dockerfile for easier testing/validation.

**Comment by brosander** [comment]
The following docker image repros it for me:
https://github.com/brosander/minifi-cpp-tooling/tree/9e5b1031d1772ccbee3ec8844a3decf232185284/Dockerfiles/ubuntu/xenial/build

```
docker build -t minifi-cpp-xenial-build .
mkdir build
docker run -ti --rm -v "$(pwd)/build:/build" minifi-cpp-xenial-build 84
```

**Comment by kevdoran** [comment]
I was able to reproduce the same behavior using the steps @brosander provided in his comment. MacOS 10.12.4 and Docker CE v 10.03.1-ce-mac5 (16048), stable, b18e2a50cc

**Comment by phrocker** [comment]
@apiri Issues experience by @brosander appear to be solved with https://github.com/phrocker/nifi-minifi-cpp/tree/minifi-274-jsoncpp. The top two commits are the necessary commits. Feel free to squash them. 
87e6b29abd688b980e7bbc512174ad9c17304742
6eb8f898b52aa10eea07d209402ea228bbf70723

**Comment by apiri** [comment]
@brosander Scope out @phrocker's work and merged into my branch which should address the build issues as per MINIFI-283.  Updated my branch/PR to include those changes.  Let us know how things look for you in the current state.

Thanks!

**Comment by brosander** [comment]
+1 works for me on bare metal Ubuntu 16.04, OSx 10.12.4, in docker container on both platforms as well

**Pull request closed without merging**
