### PR TITLE
MINIFICPP-498 Test newer compiler (gcc >= 6) (and also test build of …

### PR DESCRIPTION
**Pull request by achristianson**
…Docker image) in travis

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] If applicable, have you updated the LICENSE file?
- [x] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
Is this something to review or just that you are testing? Why is there a custom script for that release.

**Comment by achristianson** [comment]
This is ready for review. The build fails due to MINIFICPP-503. The custom script is because we're building in docker (make docker). The reason for this additional build is outlined in the ticket description.

**Comment by phrocker** [comment]
Ticket description for https://issues.apache.org/jira/browse/MINIFICPP-503, I'm guessing? I'll wait to review this one until 498 is rebased upon this, then.

**Comment by achristianson** [comment]
The general build covers an older/LTS Ubuntu which is more conservative. This way we cover old as well as new compilers.

**Comment by achristianson** [comment]
Rebased.

**Comment by achristianson** [comment]
Travis fail seems to be unrelated (segfault in C2 components).

**Pull request closed without merging**
