### PR TITLE
MINIFI-372: Replace leveldb with RocksDB

### PR DESCRIPTION
**Pull request by phrocker**
MINIFI-372: Update Cmake
MINIFI-372: Fix tests
MINIFI-372: Include deps
MINIFI-372: Rename data
MINIFI-372: Change cmake cxx flags
MINIFI-372: Fix linter issues

Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by phrocker** [comment]
Just dawned on me that I missed editing the license file....will add that shortly.

**Comment by achristianson** [comment]
Good work!

After a precursory glance at the code, nothing major sticks out. Will attempt to build and test as soon as I can get to it.

**Comment by achristianson** [comment]
Code looks good. I couldn't find any unit tests covering the rocksdb repo. With some added test coverage, I think we'd be good to go.

**Comment by phrocker** [comment]
@achristianson  should be RepoTests. Additionally, many unit tests use FlowFileRepository, which uses rocksdb the way that we do through all other repos.

**Comment by achristianson** [comment]
I see that now, thanks. What I was looking for originally was references to DatabaseContentRepository, which I didn't see.

I think we're good on FlowFileRepository coverage, but still possibly lacking on DatabaseContentRepository. There looks to be some independent/non-shared references to rocksdb there that we probably want to cover.

**Comment by phrocker** [comment]
@achristianson I completely forgot that I made it. I readied this a while ago and forgot I made this functionality, pleasantly surprised though! Thanks I'll add some tests.

**Comment by phrocker** [comment]
I'm going to add a conditional check for RocksDB. If it is already installed then we will not attempt to re-build it.

**Comment by phrocker** [comment]
@minifirocks I removed tests from being built, but did not remove the source code. I think that's a good idea. I'll also remove the docs since they aren't really necessary. Thanks!

**Comment by phrocker** [comment]
Closing to make additional changes without the fear of it being merged.

**Pull request closed without merging**
